stages:
- stage: Version
  displayName: Set Semantic Version
  jobs:
  - job: Version
    steps:
      - template: ../../steps/general/dotnet-tool.yml
        parameters:
          toolName: gitversion.tool
      - pwsh: ../dotnet-gitversion /output buildserver
        displayName: Set SemVer from git history