// <auto-generated />

using System;

using Microsoft.EntityFrameworkCore.Migrations;

namespace Esentis.BlueWaves.Persistence.Migrations
{
	public partial class SeedsAdminRole : Migration
	{
		protected override void Up(MigrationBuilder migrationBuilder)
		{
			migrationBuilder.AddColumn<bool>(
				name: "IsDeleted",
				table: "Beaches",
				type: "boolean",
				nullable: false,
				defaultValue: false);

			migrationBuilder.InsertData(
				table: "AspNetRoles",
				columns: new[] { "Id", "ConcurrencyStamp", "CreatedAt", "Name", "NormalizedName", "UpdatedAt" },
				values: new object[]
				{
					new Guid("bcb65d95-5cd1-4882-a1b5-f537cde80a22"), "e683bff6-ff91-4c1e-af8b-203cdcf0ba3c",
					new DateTimeOffset(new DateTime(2021, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
						new TimeSpan(0, 2, 0, 0, 0)),
					"ADMINISTRATOR", "ADMINISTRATOR",
					new DateTimeOffset(new DateTime(2021, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
						new TimeSpan(0, 2, 0, 0, 0))
				});
		}

		protected override void Down(MigrationBuilder migrationBuilder)
		{
			migrationBuilder.DeleteData(
				table: "AspNetRoles",
				keyColumn: "Id",
				keyValue: new Guid("bcb65d95-5cd1-4882-a1b5-f537cde80a22"));

			migrationBuilder.DropColumn(
				name: "IsDeleted",
				table: "Beaches");
		}
	}
}
