parameters:
- name: sdkVersion
  default: '5.x'
  type: string

steps:
- task: UseDotNet@2
  displayName: Install .NET SDK ${{ parameters.sdkKVersion }}
  inputs:
    packageType: 'sdk'
    version: ${{ parameters.sdkKVersion }}